version: '2'

services:
  #  redis:
  #    image: redis
  #    ports:
  #      - '6380:6379'

  mongo-express:
    image: mongo-express
    environment:
      ME_CONFIG_MONGODB_ENABLE_ADMIN: 'true'
      #      ME_CONFIG_MONGODB_AUTH_DATABASE: recruit
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: password
      ME_CONFIG_MONGODB_SERVER: mongodb-primary
      ME_CONFIG_MONGODB_PORT: 27020
    ports:
      - "18081:8081"
  mongodb-primary:
    image: 'bitnami/mongodb:4.1-ol-7'
    ports:
      - '27020:27020'
    environment:
      - MONGODB_ADVERTISED_HOSTNAME=mongodb-primary
      - MONGODB_PORT_NUMBER=27020
      - MONGODB_REPLICA_SET_MODE=primary
      - MONGODB_ROOT_PASSWORD=password
      - MONGODB_REPLICA_SET_KEY=devenv
      - MONGODB_USERNAME=cambridge
      - MONGODB_PASSWORD=cambridge
      - MONGODB_DATABASE=cambridge
    volumes:
      - 'mongodb_master_data:/bitnami'

  mongodb-secondary:
    image: 'bitnami/mongodb:4.1-ol-7'
    ports:
      - '27021:27021'
    depends_on:
      - mongodb-primary
    environment:
      - MONGODB_ADVERTISED_HOSTNAME=mongodb-secondary
      - MONGODB_REPLICA_SET_MODE=secondary
      - MONGODB_PORT_NUMBER=27021
      - MONGODB_PRIMARY_HOST=mongodb-primary
      - MONGODB_PRIMARY_PORT_NUMBER=27020
      - MONGODB_PRIMARY_ROOT_PASSWORD=password
      - MONGODB_REPLICA_SET_KEY=devenv

  mongodb-arbiter:
    image: 'bitnami/mongodb:4.1-ol-7'
    ports:
      - '27022:27022'
    depends_on:
      - mongodb-primary
    environment:
      - MONGODB_ADVERTISED_HOSTNAME=mongodb-arbiter
      - MONGODB_REPLICA_SET_MODE=arbiter
      - MONGODB_PORT_NUMBER=27022
      - MONGODB_PRIMARY_HOST=mongodb-primary
      - MONGODB_PRIMARY_PORT_NUMBER=27020
      - MONGODB_PRIMARY_ROOT_PASSWORD=password
      - MONGODB_REPLICA_SET_KEY=devenv
#  es01:
#    image: docker.elastic.co/elasticsearch/elasticsearch:7.0.1
#    environment:
#      - node.name=es01
#      - discovery.seed_hosts=es02
#      - cluster.initial_master_nodes=es01,es02
#      - cluster.name=docker-cluster
#      - bootstrap.memory_lock=true
#      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
#    ulimits:
#      memlock:
#        soft: -1
#        hard: -1
#    volumes:
#      - esdata01:/usr/share/elasticsearch/data
#    ports:
#      - 9200:9200
#    networks:
#      - esnet
#  es02:
#    image: docker.elastic.co/elasticsearch/elasticsearch:7.0.1
#    environment:
#      - node.name=es02
#      - discovery.seed_hosts=es01
#      - cluster.initial_master_nodes=es01,es02
#      - cluster.name=docker-cluster
#      - bootstrap.memory_lock=true
#      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
#    ulimits:
#      memlock:
#        soft: -1
#        hard: -1
#    volumes:
#      - esdata02:/usr/share/elasticsearch/data
#    networks:
#      - esnet
#  kibana:
#    image: docker.elastic.co/kibana/kibana:7.0.1
#    environment:
#      SERVER_NAME: localhost
#      ELASTICSEARCH_HOSTS: http://es01:9200/
#    ports:
#      - 5601:5601
#    networks:
#      - esnet

volumes:
  mongodb_master_data:
    driver: local
#  esdata01:
#    driver: local
#  esdata02:
#    driver: local

networks:
  esnet:
