version: '3'

services:

  mongo-express:
    image: mongo-express
    environment:
      ME_CONFIG_MONGODB_ENABLE_ADMIN: 'true'
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: 2jd!UT:4,?fVXV^s
      ME_CONFIG_MONGODB_SERVER: mongodb-primary
      ME_CONFIG_MONGODB_PORT: 27020
    ports:
      - "18081:8081"
    depends_on:
      - mongodb-primary
    networks:
      - crawler

  mongodb-primary:
    image: 'bitnami/mongodb:4.1-ol-7'
    ports:
      - '27020:27020'
    environment:
      - MONGODB_ADVERTISED_HOSTNAME=mongodb-primary
      - MONGODB_PORT_NUMBER=27020
      - MONGODB_REPLICA_SET_MODE=primary
      - MONGODB_ROOT_PASSWORD=2jd!UT:4,?fVXV^s
      - MONGODB_REPLICA_SET_KEY=devenv
      - MONGODB_USERNAME=cambridge
      - MONGODB_PASSWORD=2jd!UT:4,?fVXV^s
      - MONGODB_DATABASE=cambridge
    volumes:
      - 'mongodb_master_data:/bitnami'
    networks:
      - crawler

  mongodb-secondary:
    image: 'bitnami/mongodb:4.1-ol-7'
    ports:
      - '27021:27021'
    depends_on:
      - mongodb-primary
    environment:
      - MONGODB_ADVERTISED_HOSTNAME=mongodb-secondary
      - MONGODB_REPLICA_SET_MODE=secondary
      - MONGODB_PORT_NUMBER=27021
      - MONGODB_PRIMARY_HOST=mongodb-primary
      - MONGODB_PRIMARY_PORT_NUMBER=27020
      - MONGODB_PRIMARY_ROOT_PASSWORD=2jd!UT:4,?fVXV^s
      - MONGODB_REPLICA_SET_KEY=devenv
    networks:
      - crawler

  mongodb-arbiter:
    image: 'bitnami/mongodb:4.1-ol-7'
    ports:
      - '27022:27022'
    depends_on:
      - mongodb-primary
    environment:
      - MONGODB_ADVERTISED_HOSTNAME=mongodb-arbiter
      - MONGODB_REPLICA_SET_MODE=arbiter
      - MONGODB_PORT_NUMBER=27022
      - MONGODB_PRIMARY_HOST=mongodb-primary
      - MONGODB_PRIMARY_PORT_NUMBER=27020
      - MONGODB_PRIMARY_ROOT_PASSWORD=2jd!UT:4,?fVXV^s
      - MONGODB_REPLICA_SET_KEY=devenv
    networks:
      - crawler
volumes:
  mongodb_master_data:
    driver: local

networks:
  crawler:
